### ISSUE TITLE
CryFS 0.11.4 Homebrew Install Fails - Conan Error

### ISSUE THREAD

**Issue by elkfrankie** [cryfs/homebrew-tap#20]
Installing CryFS via Homebrew fails on my M1 Mac running Sonoma 14.6.1

`brew install cryfs/tap/cryfs`

`boost/1.75.0: ERROR: Package '1befd0e1e0f82b4306e5c665fd6830cb631d8a7b' build failed
boost/1.75.0: WARN: Build folder /private/tmp/cryfs-20240906-23659-v8nkum/.brew_home/.conan/data/boost/1.75.0/_/_/build/1befd0e1e0f82b4306e5c665fd6830cb631d8a7b/build-release
ERROR: boost/1.75.0: Error in build() method, line 1153
	self.run(full_command)
	ConanException: Error 1 while executing b2 -q target-os=darwin architecture=arm address-model=64 binary-format=mach-o abi=aapcs --layout=system --user-config=/private/tmp/cryfs-20240906-23659-v8nkum/.brew_home/.conan/data/boost/1.75.0/_/_/source/src/tools/build/user-config.jam -sNO_ZLIB=1 -sNO_BZIP2=1 -sNO_LZMA=1 -sNO_ZSTD=1 boost.locale.icu=off --disable-icu boost.locale.iconv=off --disable-iconv threading=multi visibility=hidden link=static variant=release --with-atomic --with-chrono --with-container --with-date_time --with-exception --with-filesystem --with-program_options --with-serialization --with-system --with-thread toolset=clang-darwin cxxstd=11 define=BOOST_SYSTEM_NO_DEPRECATED=1 define=BOOST_ASIO_NO_DEPRECATED=1 define=BOOST_FILESYSTEM_NO_DEPRECATED=1 pch=on linkflags="-stdlib=libc++" cxxflags="-fPIC -stdlib=libc++" install --prefix=/private/tmp/cryfs-20240906-23659-v8nkum/.brew_home/.conan/data/boost/1.75.0/_/_/package/1befd0e1e0f82b4306e5c665fd6830cb631d8a7b -j8 --abbreviate-paths -d0 --debug-configuration --build-dir="/private/tmp/cryfs-20240906-23659-v8nkum/.brew_home/.conan/data/boost/1.75.0/_/_/build/1befd0e1e0f82b4306e5c665fd6830cb631d8a7b/build-release"
CMake Error at cmake-utils/conan.cmake:633 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  cmake-utils/DependenciesFromConan.cmake:4 (conan_cmake_install)
  CMakeLists.txt:47 (include)`

**Comment by smessmer** [comment]
Should be fixed now
